version: '3.8'

services:
  k6:
    build: .
    volumes:
      - ./scripts:/k6/scripts
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    depends_on:
      - app
      - influxdb

  app:
    build: ./app
    ports:
      - "3000:3000"

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  grafana-storage:
